// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace LocadoraImoveisModels.Models.DataBase
{
  public partial class LocacaoimoveisContext : DbContext
  {
    public LocacaoimoveisContext()
    {
    }

    public LocacaoimoveisContext(DbContextOptions<LocacaoimoveisContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Properties> Properties { get; set; }
    public virtual DbSet<User> User { get; set; }


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
      modelBuilder.UseCollation("utf8mb4_0900_ai_ci")
          .HasCharSet("utf8mb4");

      modelBuilder.Entity<Properties>(entity =>
      {
        entity.HasKey(e => e.Idproperties)
                  .HasName("PRIMARY");

        entity.HasOne(d => d.IdUserNavigation)
                  .WithMany(p => p.Properties)
                  .HasForeignKey(d => d.IdUser)
                  .HasConstraintName("FK_Properties_User");
      });

      modelBuilder.Entity<User>(entity =>
      {
        entity.HasKey(e => e.Iduser)
                  .HasName("PRIMARY");
      });

      OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
  }
}