// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LocadoraImoveisModels.Models.DataBase
{
    [Table("user")]
    public partial class User
    {
        public User()
        {
            Properties = new HashSet<Properties>();
        }

        [Key]
        [Column("iduser")]
        public int Iduser { get; set; }
        [Required]
        [Column("userName")]
        [StringLength(256)]
        public string UserName { get; set; }
        [Required]
        [Column("userCPF")]
        [StringLength(11)]
        public string UserCpf { get; set; }
        [Required]
        [Column("userPasswordHash")]
        [StringLength(256)]
        public string UserPasswordHash { get; set; }
        [Column("adminUser")]
        public sbyte AdminUser { get; set; }

        [InverseProperty("IdUserNavigation")]
        public virtual ICollection<Properties> Properties { get; set; }
    }
}